name: CI

on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker setup
      uses: docker-practice/actions-setup-docker@master
    - name: Launch tests
      run: make all_tests
